version: 0.2
phases:
  install:
    commands:
      - echo Installing app dependencies...
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.8/2024-04-19/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --short --client
  pre_build:
    commands:
      - echo Logging into Amazon EKS...
      - aws eks --region us-west-2 update-kubeconfig --name terraformers-eks
      - echo check config
      - kubectl config view --minify
      - echo check kubectl access
      - kubectl get svc
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 962804699607.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - docker build -t terraformers .
  post_build:
    commands:
      - docker tag terraformers:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/terraformers:latest
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/terraformers:latest
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl rollout restart -f deployment.yaml
      - kubectl get svc --all-namespaces