version: 0.2
phases:
  install:
    runtime-veresions:
      terraform: 1.8.3
    commands:
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
      - unzip terraform.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
  build:
    commands:
      - echo "Building infrastructure with Terraform"
      - cd terraform/
      - terraform init
      - terraform apply --auto-approve
  post_build:
    commands:
      - echo Terraform complete `date`
      